source "https://rubygems.org"

ruby "3.2.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.1.3"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

gem 'devise'
gem 'devise-jwt'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
# gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug"
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end


gem 'rack-cors'
gem 'active_model_serializers', '~> 0.10.0'
gem 'razorpay'
gem 'dotenv-rails', groups: [:development, :test, :production]

gem 'byebug', group: [:development, :test]


gem 'nokogiri', '~> 1.13'


gem 'net-imap', '< 0.3.0'

# Gemfile
gem 'groupdate'

gem 'letter_opener', group: :development

gem 'image_processing', '~> 1.2' # Required for variants (resizing, etc.)

gem 'omniauth-google-oauth2'
gem 'omniauth'

gem 'friendly_id', '~> 5.4.0'

gem 'pdf-reader', '~> 2.11'
gem 'docx'
gem 'rtesseract'

# PDF processing
gem 'mini_magick'

gem 'kaminari'
gem 'axlsx', '~> 2.1.0.pre'
gem 'sidekiq'
gem 'sidekiq-scheduler'
gem 'roo'
gem 'roo-xls'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'

gem 'recaptcha', require: 'recaptcha/rails'

group :development do
  gem 'letter_opener_web'
end

gem "sentry-ruby"
gem "sentry-rails"
gem "sentry-sidekiq"       # (optional) for background jobs
gem 'rails_admin'
gem "sassc-rails"
gem 'geocoder'

# Google authentication
gem 'google-id-token'
# HTTP client for API requests
gem 'httparty'
gem 'activerecord-import'

# Currency and money handling
gem 'money'
gem 'faker'
gem 'paranoia', '~> 2.6'